"""migration add recruter id

Revision ID: cd8e8b3e836c
Revises: eb0cc51e14ad
Create Date: 2026-06-23 00:50:16.114220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8e8b3e836c'
down_revision: Union[str, Sequence[str], None] = 'eb0cc51e14ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_candidates_email", table_name="candidates")
    op.add_column(
        "candidates",
        sa.Column("recruiter_id", sa.UUID(), nullable=True),
    )
    op.execute(
        "UPDATE candidates "
        "SET recruiter_id = '00000000-0000-0000-0000-000000000000' "
        "WHERE recruiter_id IS NULL"
    )
    op.alter_column("candidates", "recruiter_id", nullable=False)
    op.create_index("ix_candidates_recruiter_id", "candidates", ["recruiter_id"])
    op.create_unique_constraint(
        "uq_candidate_email_recruiter", "candidates", ["email", "recruiter_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_candidate_email_recruiter", "candidates", type_="unique")
    op.drop_index("ix_candidates_recruiter_id", table_name="candidates")
    op.drop_column("candidates", "recruiter_id")
    op.create_index(op.f("ix_candidates_email"), "candidates", ["email"], unique=True)
    # ### end Alembic commands ###
